class_name LocationPresets
## Data file containing 76+ named location presets for the Dark Tide (暗潮) map generator.

# --- PRESET DATA ---
const PRESETS: Array = [
	# === CORE FORTRESSES (8) ===
	{
		"name": "天城王都", "name_en": "Tenjō Capital",
		"category": "core_fortress", "faction": "HUMAN",
		"terrain_pref": "WALL", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.45, 0.12),
		"garrison_min": 12, "garrison_max": 15, "city_def": 50, "level": 3,
		"description": "人类王国的辉煌首都",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "银冠要塞", "name_en": "Silver Crown Fortress",
		"category": "core_fortress", "faction": "HUMAN",
		"terrain_pref": "WALL", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.65, 0.22),
		"garrison_min": 10, "garrison_max": 12, "city_def": 35, "level": 3,
		"description": "守护王国北方的银色要塞",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "世界树圣地", "name_en": "World Tree Sanctuary",
		"category": "core_fortress", "faction": "HIGH_ELF",
		"terrain_pref": "FOREST", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.88, 0.35),
		"garrison_min": 10, "garrison_max": 12, "city_def": 30, "level": 3,
		"description": "高等精灵的神圣世界树",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "奥术堡垒", "name_en": "Arcane Bastion",
		"category": "core_fortress", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.50, 0.45),
		"garrison_min": 10, "garrison_max": 12, "city_def": 30, "level": 3,
		"description": "法师联盟的魔法堡垒",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "翡翠尖塔", "name_en": "Emerald Spire",
		"category": "core_fortress", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.55, 0.60),
		"garrison_min": 8, "garrison_max": 10, "city_def": 25, "level": 3,
		"description": "散发翠绿光芒的法师塔",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "碎骨王座", "name_en": "Shattered Throne",
		"category": "core_fortress", "faction": "ORC",
		"terrain_pref": "WASTELAND", "region_hint": "eternal_night",
		"position_hint": Vector2(0.20, 0.80),
		"garrison_min": 10, "garrison_max": 14, "city_def": 35, "level": 3,
		"description": "兽人部落的血腥王座",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "深渊港", "name_en": "Abyss Port",
		"category": "core_fortress", "faction": "PIRATE",
		"terrain_pref": "RIVER", "region_hint": "southern_ruins",
		"position_hint": Vector2(0.75, 0.90),
		"garrison_min": 8, "garrison_max": 10, "city_def": 25, "level": 3,
		"description": "海盗势力的深水港口",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "永夜暗城", "name_en": "Evernight Citadel",
		"category": "core_fortress", "faction": "DARK_ELF",
		"terrain_pref": "SWAMP", "region_hint": "eternal_night",
		"position_hint": Vector2(0.10, 0.55),
		"garrison_min": 12, "garrison_max": 14, "city_def": 40, "level": 3,
		"description": "暗精灵的黑暗城堡",
		"special_effects": [], "resource_type": "",
	},

	# === OUTPOST FORTRESSES (12) ===
	{
		"name": "铁壁堡", "name_en": "Iron Wall Fort",
		"category": "outpost", "faction": "HUMAN",
		"terrain_pref": "WALL", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.45, 0.30),
		"garrison_min": 8, "garrison_max": 12, "city_def": 25, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "狮鹫堡", "name_en": "Griffin Fort",
		"category": "outpost", "faction": "HUMAN",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.55, 0.25),
		"garrison_min": 8, "garrison_max": 10, "city_def": 20, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "雷鸣关", "name_en": "Thunder Pass",
		"category": "outpost", "faction": "HUMAN",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.48, 0.35),
		"garrison_min": 8, "garrison_max": 10, "city_def": 25, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "霜风哨", "name_en": "Frostwind Watch",
		"category": "outpost", "faction": "HIGH_ELF",
		"terrain_pref": "FOREST", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.82, 0.28),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "月影关", "name_en": "Moonshade Gate",
		"category": "outpost", "faction": "HIGH_ELF",
		"terrain_pref": "FOREST", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.85, 0.45),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "星落堡", "name_en": "Starfall Keep",
		"category": "outpost", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.78, 0.55),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "龙脊要塞", "name_en": "Dragon Ridge Fort",
		"category": "outpost", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.60, 0.50),
		"garrison_min": 8, "garrison_max": 10, "city_def": 20, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "焦土堡", "name_en": "Scorched Fort",
		"category": "outpost", "faction": "ORC",
		"terrain_pref": "WASTELAND", "region_hint": "eternal_night",
		"position_hint": Vector2(0.25, 0.70),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "血牙关", "name_en": "Blood Fang Pass",
		"category": "outpost", "faction": "ORC",
		"terrain_pref": "MOUNTAIN", "region_hint": "eternal_night",
		"position_hint": Vector2(0.15, 0.75),
		"garrison_min": 6, "garrison_max": 10, "city_def": 20, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "暗礁塔", "name_en": "Reef Tower",
		"category": "outpost", "faction": "PIRATE",
		"terrain_pref": "RIVER", "region_hint": "southern_ruins",
		"position_hint": Vector2(0.80, 0.80),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "霜牙港", "name_en": "Frost Fang Port",
		"category": "outpost", "faction": "PIRATE",
		"terrain_pref": "RIVER", "region_hint": "northern_wastes",
		"position_hint": Vector2(0.15, 0.15),
		"garrison_min": 6, "garrison_max": 10, "city_def": 20, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "月影祭坛", "name_en": "Moon Shadow Altar",
		"category": "outpost", "faction": "DARK_ELF",
		"terrain_pref": "SWAMP", "region_hint": "deep_coast",
		"position_hint": Vector2(0.12, 0.65),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},

	# === SPECIAL NAMED LOCATIONS (12) ===
	{
		"name": "丝路集市", "name_en": "Silk Road Market",
		"category": "special", "faction": "NEUTRAL",
		"terrain_pref": "PLAINS", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.42, 0.40),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "繁忙的贸易集散地",
		"special_effects": [], "resource_type": "",
	},
	{
		"name": "暗巷黑市", "name_en": "Shadow Alley Market",
		"category": "special", "faction": "NEUTRAL",
		"terrain_pref": "WALL", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.52, 0.55),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "鹰眼哨", "name_en": "Eagle Eye Watch",
		"category": "special", "faction": "HUMAN",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.58, 0.35),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "铁门关", "name_en": "Iron Gate Pass",
		"category": "special", "faction": "HUMAN",
		"terrain_pref": "WALL", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.46, 0.42),
		"garrison_min": 6, "garrison_max": 8, "city_def": 15, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "裂谷桥", "name_en": "Rift Bridge",
		"category": "special", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.40, 0.55),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "风语塔", "name_en": "Wind Whisper Tower",
		"category": "special", "faction": "MAGE",
		"terrain_pref": "PLAINS", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.70, 0.35),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "潮汐祭坛", "name_en": "Tide Altar",
		"category": "special", "faction": "PIRATE",
		"terrain_pref": "RIVER", "region_hint": "southern_ruins",
		"position_hint": Vector2(0.82, 0.85),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "枯木林", "name_en": "Dead Wood Forest",
		"category": "special", "faction": "DARK_ELF",
		"terrain_pref": "SWAMP", "region_hint": "eternal_night",
		"position_hint": Vector2(0.18, 0.60),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "熔岩裂隙", "name_en": "Lava Rift",
		"category": "special", "faction": "ORC",
		"terrain_pref": "VOLCANIC", "region_hint": "eternal_night",
		"position_hint": Vector2(0.28, 0.85),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "幽灵船坞", "name_en": "Ghost Docks",
		"category": "special", "faction": "DARK_ELF",
		"terrain_pref": "RIVER", "region_hint": "southern_ruins",
		"position_hint": Vector2(0.65, 0.88),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "星象台", "name_en": "Star Observatory",
		"category": "special", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.75, 0.25),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "贤者之塔", "name_en": "Sage Tower",
		"category": "special", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.82, 0.55),
		"garrison_min": 6, "garrison_max": 10, "city_def": 20, "level": 2,
		"description": "", "special_effects": [], "resource_type": "",
	},

	# === NEUTRAL LOCATIONS (6) ===
	{
		"name": "行商驿站", "name_en": "Merchant Outpost",
		"category": "neutral", "faction": "NEUTRAL",
		"terrain_pref": "PLAINS", "region_hint": "",
		"position_hint": Vector2(0.38, 0.45),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "枯骨墓穴", "name_en": "Bone Crypt",
		"category": "neutral", "faction": "NEUTRAL",
		"terrain_pref": "WASTELAND", "region_hint": "",
		"position_hint": Vector2(0.45, 0.65),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "绿影营地", "name_en": "Green Shadow Camp",
		"category": "neutral", "faction": "NEUTRAL",
		"terrain_pref": "FOREST", "region_hint": "",
		"position_hint": Vector2(0.32, 0.38),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "地精工坊", "name_en": "Goblin Workshop",
		"category": "neutral", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.62, 0.50),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "流浪马戏团", "name_en": "Wandering Circus",
		"category": "neutral", "faction": "NEUTRAL",
		"terrain_pref": "PLAINS", "region_hint": "",
		"position_hint": Vector2(0.55, 0.45),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "赏金猎人公会", "name_en": "Bounty Hunter Guild",
		"category": "neutral", "faction": "NEUTRAL",
		"terrain_pref": "WALL", "region_hint": "",
		"position_hint": Vector2(0.50, 0.38),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},

	# === BANDIT LAIRS (10) ===
	{
		"name": "黑风寨", "name_en": "Black Wind Stronghold",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.35, 0.55),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "落日盗窟", "name_en": "Sunset Bandit Den",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "WASTELAND", "region_hint": "",
		"position_hint": Vector2(0.22, 0.60),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "毒蛇谷", "name_en": "Viper Valley",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "SWAMP", "region_hint": "",
		"position_hint": Vector2(0.40, 0.72),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "暗影巢穴", "name_en": "Shadow Nest",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "FOREST", "region_hint": "",
		"position_hint": Vector2(0.15, 0.45),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "断牙山寨", "name_en": "Broken Fang Hideout",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.42, 0.68),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "腐沼堡", "name_en": "Rot Swamp Fort",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "SWAMP", "region_hint": "",
		"position_hint": Vector2(0.58, 0.78),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "秃鹫岭", "name_en": "Vulture Ridge",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "WASTELAND", "region_hint": "",
		"position_hint": Vector2(0.32, 0.85),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "海盗湾", "name_en": "Pirate Bay",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "RIVER", "region_hint": "",
		"position_hint": Vector2(0.88, 0.60),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "鬼火林", "name_en": "Will-o-Wisp Grove",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "FOREST", "region_hint": "",
		"position_hint": Vector2(0.25, 0.42),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "噬骨洞", "name_en": "Bone Eater Cave",
		"category": "bandit_lair", "faction": "BANDIT",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.65, 0.60),
		"garrison_min": 4, "garrison_max": 6, "city_def": 10, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},

	# === EVENT POINTS (10) ===
	{
		"name": "古战场遗迹", "name_en": "Ancient Battlefield",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "RUINS", "region_hint": "",
		"position_hint": Vector2(0.38, 0.58),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "神秘石碑", "name_en": "Mysterious Stele",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.60, 0.42),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "精灵遗迹", "name_en": "Elven Ruins",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "FOREST", "region_hint": "",
		"position_hint": Vector2(0.22, 0.28),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "堕落神殿", "name_en": "Fallen Temple",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "RUINS", "region_hint": "",
		"position_hint": Vector2(0.52, 0.75),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "时空裂缝", "name_en": "Time Rift",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "PLAINS", "region_hint": "",
		"position_hint": Vector2(0.45, 0.35),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "龙骨荒原", "name_en": "Dragon Bone Wastes",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "WASTELAND", "region_hint": "",
		"position_hint": Vector2(0.35, 0.68),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "远古图书馆", "name_en": "Ancient Library",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "WALL", "region_hint": "",
		"position_hint": Vector2(0.68, 0.32),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "冰封墓地", "name_en": "Frozen Cemetery",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.50, 0.10),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "魔能风暴区", "name_en": "Mana Storm Zone",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "WASTELAND", "region_hint": "",
		"position_hint": Vector2(0.75, 0.55),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "预言者洞穴", "name_en": "Prophet's Cave",
		"category": "event_point", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.58, 0.68),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},

	# === RESOURCE STATIONS (9) ===
	{
		"name": "魔晶矿脉", "name_en": "Mana Crystal Mine",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.62, 0.38),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "crystal",
	},
	{
		"name": "战马牧场", "name_en": "War Horse Ranch",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "PLAINS", "region_hint": "",
		"position_hint": Vector2(0.40, 0.32),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "horse",
	},
	{
		"name": "铁矿场", "name_en": "Iron Mine",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.30, 0.65),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "crystal",
	},
	{
		"name": "药草园", "name_en": "Herb Garden",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "FOREST", "region_hint": "",
		"position_hint": Vector2(0.28, 0.30),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "horse",
	},
	{
		"name": "灵木林场", "name_en": "Spirit Wood Mill",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "FOREST", "region_hint": "",
		"position_hint": Vector2(0.20, 0.38),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "shadow",
	},
	{
		"name": "盐田港", "name_en": "Salt Port",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "RIVER", "region_hint": "",
		"position_hint": Vector2(0.85, 0.55),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "crystal",
	},
	{
		"name": "硫磺泉", "name_en": "Sulfur Spring",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "SWAMP", "region_hint": "",
		"position_hint": Vector2(0.45, 0.78),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "gunpowder",
	},
	{
		"name": "宝石洞", "name_en": "Gem Cave",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "MOUNTAIN", "region_hint": "",
		"position_hint": Vector2(0.72, 0.45),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "crystal",
	},
	{
		"name": "魔铁锻炉", "name_en": "Mana Iron Forge",
		"category": "resource_station", "faction": "NEUTRAL",
		"terrain_pref": "WALL", "region_hint": "",
		"position_hint": Vector2(0.55, 0.62),
		"garrison_min": 3, "garrison_max": 5, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "gunpowder",
	},

	# === VILLAGES (11) ===
	{
		"name": "枫叶村", "name_en": "Maple Leaf Village",
		"category": "village", "faction": "HUMAN",
		"terrain_pref": "PLAINS", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.48, 0.18),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "晨曦镇", "name_en": "Dawn Town",
		"category": "village", "faction": "HUMAN",
		"terrain_pref": "PLAINS", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.60, 0.18),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "柳河庄", "name_en": "Willow River Manor",
		"category": "village", "faction": "HUMAN",
		"terrain_pref": "RIVER", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.52, 0.28),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "白石村", "name_en": "White Stone Village",
		"category": "village", "faction": "HIGH_ELF",
		"terrain_pref": "FOREST", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.85, 0.38),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "鹿角镇", "name_en": "Antler Town",
		"category": "village", "faction": "HIGH_ELF",
		"terrain_pref": "FOREST", "region_hint": "eastern_highlands",
		"position_hint": Vector2(0.80, 0.42),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "云雾庄", "name_en": "Cloud Mist Manor",
		"category": "village", "faction": "MAGE",
		"terrain_pref": "MOUNTAIN", "region_hint": "radiant_kingdom",
		"position_hint": Vector2(0.58, 0.52),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "碧水村", "name_en": "Azure Water Village",
		"category": "village", "faction": "PIRATE",
		"terrain_pref": "RIVER", "region_hint": "southern_ruins",
		"position_hint": Vector2(0.78, 0.85),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "红叶镇", "name_en": "Red Leaf Town",
		"category": "village", "faction": "ORC",
		"terrain_pref": "WASTELAND", "region_hint": "eternal_night",
		"position_hint": Vector2(0.22, 0.78),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "松风庄", "name_en": "Pine Wind Manor",
		"category": "village", "faction": "DARK_ELF",
		"terrain_pref": "SWAMP", "region_hint": "eternal_night",
		"position_hint": Vector2(0.14, 0.58),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "星落村", "name_en": "Starfall Village",
		"category": "village", "faction": "NEUTRAL",
		"terrain_pref": "PLAINS", "region_hint": "",
		"position_hint": Vector2(0.42, 0.48),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
	{
		"name": "银溪镇", "name_en": "Silver Brook Town",
		"category": "village", "faction": "NEUTRAL",
		"terrain_pref": "RIVER", "region_hint": "",
		"position_hint": Vector2(0.68, 0.65),
		"garrison_min": 2, "garrison_max": 4, "city_def": 5, "level": 1,
		"description": "", "special_effects": [], "resource_type": "",
	},
]


# --- HELPER FUNCTIONS ---

static func get_presets_by_category(category: String) -> Array:
	var result: Array = []
	for p in PRESETS:
		if p["category"] == category:
			result.append(p)
	return result


static func get_presets_by_faction(faction: String) -> Array:
	var result: Array = []
	for p in PRESETS:
		if p["faction"] == faction:
			result.append(p)
	return result


static func get_preset_count() -> int:
	return PRESETS.size()
