#!/usr/bin/env python3
"""
Dark Tide SLG — Generate Godot .import override files for WebP assets.
Sets VRAM compression, mipmaps, and size limits per asset category.

Usage:
    python3 tools/generate_import_overrides.py [--dry-run]

Run AFTER compress_assets.py to configure how Godot imports the new WebP files.
"""

import argparse
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = PROJECT_ROOT / "assets"

# Import presets per directory
# max_size: Godot will downscale textures larger than this on import
# mipmaps: enable for 3D/zoomed assets, disable for fixed-size UI
# compress_mode: 0=lossless, 1=lossy, 2=VRAM, 3=uncompressed
IMPORT_PRESETS = {
    "effects": {
        "compress_mode": 2,  # VRAM compressed (GPU-friendly, smaller in memory)
        "max_size": 1024,     # Downscale effects to max 1024px
        "mipmaps": False,
        "filter": True,
    },
    "characters/animations": {
        "compress_mode": 2,
        "max_size": 1024,
        "mipmaps": False,
        "filter": True,
    },
    "characters/designs": {
        "compress_mode": 1,   # Lossy (preserve quality for key art)
        "max_size": 2048,
        "mipmaps": False,
        "filter": True,
    },
    "characters/heads": {
        "compress_mode": 1,
        "max_size": 512,
        "mipmaps": False,
        "filter": True,
    },
    "characters/chibi": {
        "compress_mode": 1,
        "max_size": 512,
        "mipmaps": False,
        "filter": True,
    },
    "characters/battles": {
        "compress_mode": 1,
        "max_size": 512,
        "mipmaps": False,
        "filter": True,
    },
    "icons": {
        "compress_mode": 0,   # Lossless (pixel-perfect icons)
        "max_size": 0,        # No downscale
        "mipmaps": False,
        "filter": False,      # Nearest-neighbor for pixel art
    },
    "ui": {
        "compress_mode": 0,
        "max_size": 0,
        "mipmaps": False,
        "filter": True,
    },
    "map": {
        "compress_mode": 2,
        "max_size": 1024,
        "mipmaps": True,      # Map tiles benefit from mipmaps when zoomed out
        "filter": True,
    },
    "vfx": {
        "compress_mode": 2,
        "max_size": 512,
        "mipmaps": False,
        "filter": True,
    },
    "sprites": {
        "compress_mode": 0,
        "max_size": 0,
        "mipmaps": False,
        "filter": False,
    },
}

IMPORT_TEMPLATE = """; Generated by tools/generate_import_overrides.py
; Do not edit manually — re-run the script to update.
[remap]

importer="texture"
type="CompressedTexture2D"
uid="{uid}"
path="{import_path}"

[deps]

source_file="{source_file}"
dest_files=["{import_path}"]

[params]

compress/mode={compress_mode}
compress/high_quality=false
compress/lossy_quality=0.7
compress/hdr_compression=1
compress/normal_map=0
compress/channel_pack=0
mipmaps/generate={mipmaps}
mipmaps/limit=-1
roughness/mode=0
roughness/src_normal=""
process/fix_alpha_border=true
process/premult_alpha=false
process/normal_map_invert_y=false
process/hdr_as_srgb=false
process/hdr_clamp_exposure=false
process/size_limit={max_size}
detect_3d/compress_to=1
"""


def get_preset(rel_path: str) -> dict:
    """Get import preset for a file based on its path."""
    rel_lower = rel_path.replace("\\", "/").lower()
    for prefix in sorted(IMPORT_PRESETS.keys(), key=len, reverse=True):
        if rel_lower.startswith(prefix):
            return IMPORT_PRESETS[prefix]
    return IMPORT_PRESETS.get("_default", {
        "compress_mode": 1, "max_size": 1024, "mipmaps": False, "filter": True
    })


def generate_uid(path_str: str) -> str:
    """Generate a deterministic UID from the file path."""
    h = hash(path_str) & 0xFFFFFFFFFFFF  # 48-bit hash
    return f"uid://{h:012x}"


def main():
    parser = argparse.ArgumentParser(description="Generate Godot import overrides")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    # Find all image files (both png and webp)
    image_files = []
    for ext in ("*.png", "*.webp"):
        image_files.extend(ASSETS_DIR.rglob(ext))

    created = 0
    skipped = 0

    for img in sorted(image_files):
        rel = str(img.relative_to(PROJECT_ROOT)).replace("\\", "/")
        rel_assets = str(img.relative_to(ASSETS_DIR)).replace("\\", "/")
        preset = get_preset(rel_assets)

        import_path = f".godot/imported/{img.stem}.{img.suffix[1:]}-{hash(rel) & 0xFFFFFFFF:08x}.ctex"
        source_file = f"res://{rel}"
        uid = generate_uid(rel)

        content = IMPORT_TEMPLATE.format(
            uid=uid,
            import_path=import_path,
            source_file=source_file,
            compress_mode=preset["compress_mode"],
            mipmaps="true" if preset["mipmaps"] else "false",
            max_size=preset["max_size"],
        )

        import_file = img.parent / (img.name + ".import")

        if import_file.exists():
            skipped += 1
            continue

        if args.dry_run:
            print(f"  [DRY] {import_file.relative_to(PROJECT_ROOT)}")
        else:
            import_file.write_text(content, encoding="utf-8")

        created += 1

    action = "Would create" if args.dry_run else "Created"
    print(f"\n{action} {created} .import files, skipped {skipped} existing")
    print("NOTE: .import files are managed by Godot editor. These overrides")
    print("      will be applied when you open the project in Godot.")


if __name__ == "__main__":
    main()
